### ISSUE TITLE
Script fails for Ownership Statement relationships when Interest Type and Interest Details are missing

### ISSUE THREAD

**Issue by kaerumy** [Sinar/popit_relationship#37]
```
Traceback (most recent call last):
  File "bin/primport", line 8, in <module>
    sys.exit(main())
  File "/home/kaeru/dev/relationships/lib/python3.8/site-packages/popit_relationship/primport.py", line 135, in main
    loop.run_until_complete(app())
  File "/home/kaeru/dev/relationships/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/kaeru/dev/relationships/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/kaeru/dev/relationships/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kaeru/dev/relationships/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kaeru/dev/relationships/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/kaeru/dev/relationships/lib/python3.8/site-packages/popit_relationship/primport.py", line 117, in save
    session.write_transaction(db.graph_save, graph_init())
  File "/home/kaeru/dev/relationships/lib/python3.8/site-packages/neo4j/work/simple.py", line 403, in write_transaction
    return self._run_transaction(WRITE_ACCESS, transaction_function, *args, **kwargs)
  File "/home/kaeru/dev/relationships/lib/python3.8/site-packages/neo4j/work/simple.py", line 309, in _run_transaction
    result = transaction_function(tx, *args, **kwargs)
  File "/home/kaeru/dev/relationships/lib/python3.8/site-packages/popit_relationship/db.py", line 23, in graph_save
    node_save_relationship(tx, graph, node, dest, key)
  File "/home/kaeru/dev/relationships/lib/python3.8/site-packages/popit_relationship/db.py", line 55, in node_save_relationship
    tx.run(
  File "/home/kaeru/dev/relationships/lib/python3.8/site-packages/neo4j/work/transaction.py", line 118, in run
    result._tx_ready_run(query, parameters, **kwparameters)
  File "/home/kaeru/dev/relationships/lib/python3.8/site-packages/neo4j/work/result.py", line 57, in _tx_ready_run
    self._run(query, parameters, None, None, None, **kwparameters)
  File "/home/kaeru/dev/relationships/lib/python3.8/site-packages/neo4j/work/result.py", line 101, in _run
    self._attach()
  File "/home/kaeru/dev/relationships/lib/python3.8/site-packages/neo4j/work/result.py", line 202, in _attach
    self._connection.fetch_message()
  File "/home/kaeru/dev/relationships/lib/python3.8/site-packages/neo4j/io/_bolt4x1.py", line 353, in fetch_message
    response.on_failure(summary_metadata or {})
  File "/home/kaeru/dev/relationships/lib/python3.8/site-packages/neo4j/io/_bolt4x1.py", line 541, in on_failure
    raise Neo4jError.hydrate(**metadata)
neo4j.exceptions.CypherSyntaxError: {code: Neo.ClientError.Statement.SyntaxError} {message: Invalid input '}': expected whitespace, comment or a property key name (line 6, column 56 (offset: 217))
"                    {predicate: $predicate, key: $key, }]->"

```

**Comment by Jeffrey04** [comment]
lemme check, missed notification on this, sorry

**Comment by Jeffrey04** [comment]
thanks for the precise title heh, found the problem in code

1. while the code knows to assign a default value (`None` in this case) when the fields are missing
2. it doesn't know it should store that value (like how it should be done when subject/predicate is empty)

will commit the code to attempt to fix it for control statement, and other types soon
