### ISSUE TITLE
Error in sync for Relationships for Politikus

### ISSUE THREAD

**Issue by kaerumy** [Sinar/popit_relationship#42]
```
Fetching from https://politikus.sinarproject.org/@search?portal_type=Relationship&fullobjects=1&b_start=50
Traceback (most recent call last):
  File "bin/primport", line 8, in <module>
    sys.exit(main())
  File "/home/kaeru/dev/primport-politikus/lib/python3.8/site-packages/popit_relationship/primport.py", line 135, in main
    loop.run_until_complete(app())
  File "/home/kaeru/dev/primport-politikus/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/kaeru/dev/primport-politikus/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/kaeru/dev/primport-politikus/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kaeru/dev/primport-politikus/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kaeru/dev/primport-politikus/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kaeru/dev/primport-politikus/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/kaeru/dev/primport-politikus/lib/python3.8/site-packages/popit_relationship/common.py", line 16, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/kaeru/dev/primport-politikus/lib/python3.8/site-packages/popit_relationship/sync.py", line 32, in all_sync
    await tree_import(TYPE_RELATIONSHIP, "Relationship", relationship_build_node)
  File "/home/kaeru/dev/primport-politikus/lib/python3.8/site-packages/popit_relationship/sync.py", line 365, in tree_import
    tree_insert(graph, **await tree_build(portal_type, node_builder, session))
  File "/home/kaeru/dev/primport-politikus/lib/python3.8/site-packages/popit_relationship/sync.py", line 354, in tree_build
    [node_builder(entity) for entity in await fetch(portal_type, session)],
  File "/home/kaeru/dev/primport-politikus/lib/python3.8/site-packages/popit_relationship/sync.py", line 354, in <listcomp>
    [node_builder(entity) for entity in await fetch(portal_type, session)],
  File "/home/kaeru/dev/primport-politikus/lib/python3.8/site-packages/popit_relationship/sync.py", line 228, in relationship_build_node
    "object": relationship["relationship_object"]["@id"],
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Jeffrey04** [comment]
hmm, likely some field went missing
there's a revision to the data lately?
let me check tomorrow

**Comment by kaerumy** [comment]
Last url in sync https://politikus.sinarproject.org/@@search?portal_type=Relationship&fullobjects=1&b_start=50

**Comment by Jeffrey04** [comment]
The required field is not found
```
  28   │       "@id": "https://politikus.sinarproject.org/persons/khadijah-mohd-noor/khadijah-mohd-noor-is-wife-of-abdul-azeez-abdul-rahim",
```
